name: Auto Update and Merge

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: feature-branch

      - name: Ensure feature branch is different from main
        run: |
          git fetch origin main
          if git diff --quiet origin/main; then
            echo "No changes detected, forcing a minor update."
            date > auto_update.log  # 明示的に変更を加える
            git add auto_update.log
            git commit -m "Forced update to create a PR"
            git push origin feature-branch
          else
            echo "Changes detected, skipping forced update."
          fi

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: feature-branch
          title: "Auto-generated PR"
          body: "This PR was automatically generated and merged."
          labels: automated
          draft: false
          commit-message: "Automated PR update"

      - name: Debug PR creation
        run: |
          echo "PR created with operation: ${{ steps.create_pr.outputs.pull-request-operation }}"

      - name: Auto Merge PR
        if: steps.create_pr.outputs.pull-request-number != ''
        run: |
          echo "Merging PR #${{ steps.create_pr.outputs.pull-request-number }}"
          gh pr merge --auto --squash --delete-branch --repo ${{ github.repository }} ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
