name: Auto Update and Merge

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: feature-branch

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Force sync feature-branch with main
        run: |
          git fetch origin main
          git checkout feature-branch
          git reset --hard origin/main  # feature-branch を main に完全同期
          echo "Forced update at $(date)" > auto_update.log  # 確実に変更を加える
          git add auto_update.log
          git commit -m "Forced update to create a PR"
          git push --force origin feature-branch  # 強制プッシュ

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: feature-branch
          title: "Auto-generated PR"
          body: "This PR was automatically generated and merged."
          labels: automated
          draft: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug PR creation
        run: |
          echo "PR created with operation: ${{ steps.create_pr.outputs.pull-request-operation }}"

      - name: Auto Merge PR
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        run: |
          echo "Merging PR #${{ steps.create_pr.outputs.pull-request-number }}"
          gh pr merge --auto --squash --delete-branch --repo ${{ github.repository }} ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
