name: Auto Update and Merge

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # 明示的にリポジトリを指定
          token: ${{ secrets.GITHUB_TOKEN }}  # 認証を追加
          ref: feature-branch  # 変更対象のブランチ

      - name: Modify a file
        run: |
          echo "$(date)" >> auto_update.log
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add auto_update.log
          git commit -m "Automated update at $(date)" || echo "No changes to commit"
          git push origin feature-branch

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main  # マージ先のブランチ
          branch: feature-branch  # PRを作成するブランチ
          title: "Auto-generated PR"
          body: "This PR was automatically generated and merged."
          labels: automated
          draft: false

      - name: Auto Merge PR
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        run: |
          gh pr merge --auto --squash --delete-branch --repo ${{ github.repository }} ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
